CREATE USER 'civicrm'@'localhost' IDENTIFIED BY 'admin1234';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON civicrm.* TO 'civicrm'@'localhost' IDENTIFIED BY 'admin1234';
FLUSH PRIVILEGES;
