default['compucorp']['test_password'] = 'admin1234'
default['compucorp']['logsbucket'] = 'logsbucket'
default['compucorp']['backupsbucket'] = 'backupsbucket'
default['compucorp']['drupal_home'] = '/var/www/html'
default['compucorp']['home_dir'] = '/opt/compucorp'
default['compucorp']['check_files'] = '/opt/compucorp/check_files'
default['compucorp']['db_scripts'] = '/opt/compucorp/db_scripts'
default['compucorp']['host'] = '127.0.0.1'
default['compucorp']['user'] = 'ubuntu'
default['compucorp']['civicrm_package'] = 'civicrm-4.7.12-drupal.tar.gz'
default['compucorp']['drupal_backups'] = 'public-projects/compucorp/drupal_backups'
default['compucorp']['nginx_logs'] = 'public-projects/compucorp/nginx_logs'
default['compucorp']['mysql_backups'] = 'public-projects/compucorp/mysql_backups'
default['compucorp']['php_version'] = '5.6'
# Hardcoded password only for testing purposes
